name: example
description: A new Jaspr project
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  jaspr: ^0.22.1
  jaspr_router: ^0.8.1
  jaspr_localizations:
    path: ../
  universal_web: ^1.1.1+1

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.7
  jaspr_builder: ^0.22.1
  jaspr_lints: ^0.6.0
  lints: ^6.0.0

jaspr:
  mode: static

jaspr_localizations:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: lib/l10n/generated/app_l10n.dart
  output-class: AppL10n
